In [1]:
pip list

Package                       Version
----------------------------- -----------
absl-py                       2.3.0
aiohappyeyeballs              2.4.4
aiohttp                       3.11.10
aiosignal                     1.2.0
altair                        5.5.0
anaconda-anon-usage           0.7.1
anaconda-auth                 0.8.6
anaconda-catalogs             0.2.0
anaconda-cli-base             0.5.2
anaconda-client               1.13.0
anaconda-navigator            2.6.6
anaconda-project              0.11.1
annotated-types               0.6.0
antlr4-python3-runtime        4.9.3
anyio                         4.7.0
archspec                      0.2.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     3.0.0
astunparse                    1.6.3
async-lru                     2.0.4
attrs                         23.2.0
babel                         2.16.0
backports.functools-lru-cache 1.6.4
backports.tarfile             0.0.0
backports.te

In [2]:
import pandas as pd

In [4]:
pd.__version__

'2.3.3'

In [5]:
import numpy as np
arr = np.arange(100, 105)
arr

array([100, 101, 102, 103, 104])

In [6]:
s = pd.Series(arr)
s

0    100
1    101
2    102
3    103
4    104
dtype: int64

In [7]:
s = pd.Series(arr, dtype='int32')
s

0    100
1    101
2    102
3    103
4    104
dtype: int32

In [8]:
s = pd.Series(['부장', '차장', '대리', '사원', '인턴'])
s

0    부장
1    차장
2    대리
3    사원
4    인턴
dtype: object

In [9]:
s = pd.Series([91, 2.5, '스포츠', 4, 5.16])
s

0      91
1     2.5
2     스포츠
3       4
4    5.16
dtype: object

In [10]:
s = pd.Series(['부장', '차장', '대리', '사원', '인턴'])
s

0    부장
1    차장
2    대리
3    사원
4    인턴
dtype: object

In [11]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
s[0]

'부장'

In [13]:
s[[1, 3]]

1    차장
3    사원
dtype: object

In [14]:
s[1:3]

1    차장
2    대리
dtype: object

In [15]:
s[np.arange(1, 4, 2)]

1    차장
3    사원
dtype: object

In [16]:
np.random.seed(0)
s = pd.Series(np.random.randint(10000, 20000, size=(10,)))
s

0    12732
1    19845
2    13264
3    14859
4    19225
5    17891
6    14373
7    15874
8    16744
9    13468
dtype: int32

In [18]:
rng = np.random.default_rng(0)
rng.integers(10000,20001,10)

array([18507, 16370, 15111, 12698, 13078, 10409, 10752, 10165, 11752,
       18133])

In [20]:
rng = np.random.default_rng(0)
s =pd.Series(rng.integers(10000,20001,10))
s

0    18507
1    16370
2    15111
3    12698
4    13078
5    10409
6    10752
7    10165
8    11752
9    18133
dtype: int64

In [21]:
s > 15000

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
dtype: bool

In [22]:
s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'], index=['a', 'b', 'c', 'd', 'e'])
s

a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

In [23]:
s['d']

'기획'

In [24]:
s[3]

C:\Users\User\AppData\Local\Temp\ipykernel_22104\3172538273.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[3]


'기획'

In [25]:
s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'])
s.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
s.index = list('abcde')

In [28]:
s

a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

In [29]:
s.values

array(['마케팅', '경영', '개발', '기획', '인사'], dtype=object)

In [30]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [31]:
s = pd.Series(['선화', '강호', np.nan, '소정', '우영'])
s

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: object

In [33]:
s.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [34]:
s.isna()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [35]:
s[s.isnull()]

2    NaN
dtype: object

In [36]:
s[s.isna()]

2    NaN
dtype: object

In [37]:
s.notnull()

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [38]:
s.notna()

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [39]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: object

In [40]:
s = pd.Series(np.arange(100, 150, 10))
s

0    100
1    110
2    120
3    130
4    140
dtype: int64

In [41]:
s[1:3]

1    110
2    120
dtype: int64

In [45]:
s.index = list('가나다라마')
s

가    100
나    110
다    120
라    130
마    140
dtype: int64

In [46]:
s['나':'라']

나    110
다    120
라    130
dtype: int64

In [48]:
arr = np.arange(3, 12, 2)
arr

array([ 3,  5,  7,  9, 11])

In [49]:
pd.Series(arr, dtype='float32')

0     3.0
1     5.0
2     7.0
3     9.0
4    11.0
dtype: float32

In [50]:
pd.Series(['가','나','다','라','마'])

0    가
1    나
2    다
3    라
4    마
dtype: object

In [89]:
sample = pd.Series(np.arange(10,51,10), dtype='int64', index=['가','나','다','라','마'])
sample

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [91]:
sample[['나','라']]

나    20
라    40
dtype: int64

In [92]:
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100, 200, size=(15,)))
sample2

0     199
1     190
2     115
3     195
4     128
5     190
6     109
7     120
8     175
9     122
10    171
11    134
12    196
13    140
14    185
dtype: int32

In [93]:
sample2[sample2 < 160]

2     115
4     128
6     109
7     120
9     122
11    134
13    140
dtype: int32

In [100]:
sample2[(sample2 >= 130) & (sample2 <= 170)]

11    134
13    140
dtype: int32

In [104]:
sample3 = pd.Series(['apple', np.nan, 'banana', 'kiwi', 'gubong'], index=['가','나','다','라','마'])
sample3

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [58]:
pd.DataFrame([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [59]:
pd.DataFrame([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]], columns=['가', '나', '다'])

가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

In [60]:
data = {
    'name': ['Kim', 'Lee', 'Park'], 
    'age': [24, 27, 34], 
    'children': [2, 1, 3]
}

In [63]:
df = pd.DataFrame(data)

In [64]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [65]:
df.columns

Index(['name', 'age', 'children'], dtype='object')

In [66]:
df.values

array([['Kim', 24, 2],
       ['Lee', 27, 1],
       ['Park', 34, 3]], dtype=object)

In [67]:
df.dtypes

name        object
age          int64
children     int64
dtype: object

In [68]:
df.T

0    1     2
name      Kim  Lee  Park
age        24   27    34
children    2    1     3

In [69]:
df.index = list('abc')
df

name  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

In [70]:
df['name']

a     Kim
b     Lee
c    Park
Name: name, dtype: object

In [71]:
type(df['name'])

pandas.core.series.Series

In [72]:
df[['name', 'children']]

name  children
a   Kim         2
b   Lee         1
c  Park         3

In [77]:
df.rename(columns={'name': '이름'}, inplace=True)

In [78]:
df

이름  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

In [79]:
bg = {
    'food': ['KFC', 'McDonald', 'SchoolFood'], 
    'price': [1000, 2000, 2500], 
    'rating': [4.5, 3.9, 4.2]
}
pd.DataFrame(bg)

food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

In [80]:
bg= pd.DataFrame(bg)

In [81]:
bg[['food','rating']]

food  rating
0         KFC     4.5
1    McDonald     3.9
2  SchoolFood     4.2

In [86]:
bg.rename(columns={'food':'place'}, inplace=True)

In [87]:
bg

place  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2