In [1]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


### 마크다운 샵 3

In [2]:
import numpy as np # 넘파이 임포오트

In [3]:
import matplotlib.pyplot as plt

In [1]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


In [4]:
pip list

Package                       Version
----------------------------- -----------
absl-py                       2.3.0
aiohappyeyeballs              2.4.4
aiohttp                       3.11.10
aiosignal                     1.2.0
altair                        5.5.0
anaconda-anon-usage           0.7.1
anaconda-auth                 0.8.6
anaconda-catalogs             0.2.0
anaconda-cli-base             0.5.2
anaconda-client               1.13.0
anaconda-navigator            2.6.6
anaconda-project              0.11.1
annotated-types               0.6.0
antlr4-python3-runtime        4.9.3
anyio                         4.7.0
archspec                      0.2.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     3.0.0
astunparse                    1.6.3
async-lru                     2.0.4
attrs                         23.2.0
babel                         2.16.0
backports.functools-lru-cache 1.6.4
backports.tarfile             0.0.0
backports.te

In [1]:
import numpy as np
print(np.__version__)

2.3.5


In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a.shape

(6,)

In [9]:
b = np.array([[1, 2, 3, 4, 5, 6]])
b

array([[1, 2, 3, 4, 5, 6]])

In [10]:
b.shape

(1, 6)

In [11]:
a

array([1, 2, 3, 4, 5, 6])

In [12]:
a[0]

np.int64(1)

In [14]:
a[0]=5
a

array([5, 2, 3, 4, 5, 6])

In [15]:
a[:2]

array([5, 2])

In [17]:
b = a[3:]
b

array([4, 5, 6])

In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a.shape

(3, 4)

In [20]:
a.ndim

2

In [21]:
a.size

12

In [22]:
a.dtype

dtype('int64')

In [23]:
np.zeros(2)

array([0., 0.])

In [26]:
np.ones((3,4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.empty(2)

array([1., 1.])

In [28]:
np.arange(4)

array([0, 1, 2, 3])

In [29]:
np.arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.linspace(0, 15, num=9)

array([ 0.   ,  1.875,  3.75 ,  5.625,  7.5  ,  9.375, 11.25 , 13.125,
       15.   ])

In [33]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [36]:
a = np.array((1, 2, 3, 4))
a

array([1, 2, 3, 4])

In [37]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [38]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [39]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [40]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
arr = np.arange(1, 13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr.shape

(3, 4)

In [46]:
arr2 = arr.reshape(4,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

arr3 = arr.reshape(3,5)
arr3

In [48]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [49]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [52]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [53]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [54]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [55]:
np.sort(a)

array([[1, 4],
       [1, 3]])

In [56]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [58]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [59]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [62]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [63]:
# np.concatenate((x,y), axis=1) 열의 갯수가 맞지 않아서 실행이 안됨

In [64]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [66]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [67]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [68]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [69]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [70]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [71]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [72]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [73]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [74]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [75]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [77]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [78]:
data[0]

np.int64(1)

In [79]:
data[0:1]

array([1])

In [80]:
data[1:]

array([2, 3])

In [81]:
data[:-1]

array([1, 2])

In [82]:
c = np.arange(12).reshape(3,4)

In [83]:
c[1,2]

np.int64(6)

In [84]:
c[1:2, 2:3]

array([[6]])

In [86]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
# a[a < 5] -> 불리언 인덱싱
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
a[a<5]

array([1, 2, 3, 4])

In [89]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [90]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [92]:
a > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
a < 11

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [93]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
five_up = (a > 5) | (a == 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [98]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [101]:
arr1[0]=15
arr1

array([15,  5,  6,  7,  8])

In [102]:
a

array([ 1,  2,  3, 15,  5,  6,  7,  8,  9, 10])

In [103]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
a1,a2

(array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]]))

In [104]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [105]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [106]:
a1 = np.array([[1, 1, 1],
               [2, 2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
a1,a2

(array([[1, 1, 1],
        [2, 2, 2]]),
 array([[3, 3],
        [4, 4]]))

In [107]:
# np.vstack((a1,a2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [108]:
np.hstack((a1,a2))

array([[1, 1, 1, 3, 3],
       [2, 2, 2, 4, 4]])

In [109]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [110]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [111]:
# np.hsplit(x, 5)

ValueError: array split does not result in an equal division

In [112]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [113]:
np.hsplit(x, (5, 7))

[array([[ 1,  2,  3,  4,  5],
        [13, 14, 15, 16, 17]]),
 array([[ 6,  7],
        [18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

In [115]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [117]:
b1[2]=55
b1

array([ 1,  2, 55,  4])

In [118]:
a

array([[ 1,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
b2 = a.copy()
b2

array([[ 1,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
b2[0,0]=33

In [121]:
b2

array([[33,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
a

array([[ 1,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data, ones


(array([1, 2]), array([1, 1]))

In [124]:
data + ones

array([2, 3])

In [125]:
data - ones

array([0, 1])

In [126]:
data * ones

array([1, 2])

In [127]:
data / ones

array([1., 2.])

In [129]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [130]:
a.sum()

np.int64(10)

In [131]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [132]:
b.sum(axis=0)

array([3, 3])

In [133]:
b.sum(axis=1)

array([2, 4])

In [134]:
b.sum()

np.int64(6)

In [135]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [136]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a,b

(array([[ 0.,  0.,  0.],
        [10., 10., 10.],
        [20., 20., 20.],
        [30., 30., 30.]]),
 array([1., 2., 3.]))

In [137]:
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [138]:
# a = np.array([[ 0.0,  0.0,  0.0],
#               [10.0, 10.0, 10.0],
#               [20.0, 20.0, 20.0],
#               [30.0, 30.0, 30.0]])
# b = np.array([1.0, 2.0, 3.0, 4.0])
# # a+b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [139]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0, 4.0]).reshape(4,1)
a + b

array([[ 1.,  1.,  1.],
       [12., 12., 12.],
       [23., 23., 23.],
       [34., 34., 34.]])

In [140]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a, b

(array([ 0., 10., 20., 30.]), array([1., 2., 3.]))

In [141]:
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [142]:
observation = np.array([111.0, 188.0])
codes = np.array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
diff

array([[ -9.,  15.],
       [ 21.,   5.],
       [-66., -33.],
       [-54., -15.]])

In [143]:
dist = np.sqrt(np.sum(diff**2,axis=-1))
np.argmin(dist)

np.int64(0)

In [144]:
np.sum(diff**2)

np.float64(9358.0)

In [145]:
np.sum(diff**2,axis=-1)

array([ 306.,  466., 5445., 3141.])

In [146]:
np.sqrt(np.sum(diff**2,axis=-1))

array([17.49285568, 21.58703314, 73.79024326, 56.04462508])

In [152]:
dist = np.sqrt(np.sum(diff**2,axis=-1))
dist
np.argmin(dist)

np.int64(0)

In [151]:
argmin(dist)

NameError: name 'argmin' is not defined